version: "3.9"

services:
  asp-react-oidc-keycloakdb:
    container_name: asp-react-oidc-keycloakdb
    image: postgres:12.9
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    ports:
      - 52432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h asp-react-oidc-keycloakdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - asp-react-oidc-network

  asp-react-oidc-keycloak:
    container_name: asp-react-oidc-keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://asp-react-oidc-keycloakdb:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: PdZoV9NpYuq#zdsYXfHo
      KC_FEATURES:
        token-exchange
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_CACHE_STACK: tcp
    volumes:
      - ./.keycloak:/opt/keycloak/data/import/:ro
    command:
      - "start"
      - "--http-port 8080"
      - "--proxy=passthrough"
      - "--import-realm"
    ports:
      - 52433:8080
    depends_on:
      - asp-react-oidc-keycloakdb
    networks:
      - asp-react-oidc-network

  asp-react-oidc-backend:
    container_name: asp-react-oidc-backend
    image: asp-react-oidc-backend
    build: ./src/backend
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://asp-react-oidc-backend:80/healthcheck" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      AUTHORITY: http://asp-react-oidc-keycloak:8080/realms/react-example
      AUDIENCE: backend
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - asp-react-oidc-keycloak
    volumes:
      - ~/.vscode/extensions/ms-dotnettools.csharp-1.25.4-linux-x64/.debugger:/remote_debugger:rw
    ports:
      - "52434:80"
    networks:
      - asp-react-oidc-network

  asp-react-oidc-web:
    container_name: asp-react-oidc-web
    image: asp-react-oidc-web
    build: 
      context: ./src/react
      args:
        REACT_APP_KEYCLOAK_CLIENT_ID: react
        REACT_APP_KEYCLOAK_URL: http://localhost:52433/realms/react-example
        REACT_APP_BACKEND_URL: http://localhost:52434
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "52435:3000"
    depends_on:
      - asp-react-oidc-keycloak
    networks:
      - asp-react-oidc-network

networks:
  asp-react-oidc-network:
    name: asp-react-oidc-network
    driver: bridge

volumes:
  keycloakdb:
    driver: local