apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
    kompose.service.expose: asp-react-oidc.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: asp-react-oidc-web
  name: asp-react-oidc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: asp-react-oidc-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
        kompose.service.expose: asp-react-oidc.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/asp-react-oidc-network: "true"
        io.kompose.service: asp-react-oidc-web
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: http://backend.asp-react-oidc.test
            - name: REACT_APP_KEYCLOAK_CLIENT_ID
              value: react
            - name: REACT_APP_KEYCLOAK_URL
              value: http://keycloak.asp-react-oidc.test/realms/react-example
          image: {{ .Values.werf.image.asp_react_oidc_web }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3000
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: asp-react-oidc-web
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
